version: "3.3"

services:
  app:
    build: .
    ports:
      - "80:8000"
    container_name: app
    environment:
      - ENV_FOR_DYNACONF
      - MYSQL_DATABASE
      - MYSQL_HOST
      - MYSQL_PASSWORD
      - MYSQL_USER
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENTE_SECRET
    volumes:
      - .:/app
    restart: always
    command: tail -f /dev/null
  db:
    image: mysql:5.7
    restart: always
    container_name: mydb
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql
